apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: default
  labels:
    app: api-server
spec:
  type: NodePort
  selector:
    app: api-server
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30500
    protocol: TCP
