---
# ServiceAccount for collector
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: default
  labels:
    app: collector
---
# ClusterRole for collector
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collector
  labels:
    app: collector
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
# ClusterRoleBinding for collector
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collector
  labels:
    app: collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collector
subjects:
- kind: ServiceAccount
  name: collector
  namespace: default
---
# DaemonSet for collector
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collector
  namespace: default
  labels:
    app: collector
spec:
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      serviceAccount: collector
      hostNetwork: true
      hostPID: true
      containers:
      - name: collector
        image: woongcheol99/k8s_collector:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: API_SERVER_URL
          value: "http://10.100.190.130:5000"
        - name: COLLECTION_INTERVAL
          value: "5"
        - name: LOG_LEVEL
          value: "INFO"
        - name: API_TIMEOUT
          value: "10"
        - name: API_RETRY_COUNT
          value: "3"
        - name: EXCLUDE_NAMESPACES
          value: "kube-system,kube-public"
        - name: ENABLE_DISK_IO
          value: "true"
        - name: ENABLE_NETWORK_IO
          value: "true"
        - name: DEBUG_MODE
          value: "false"
        - name: DRY_RUN
          value: "false"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: proc
          mountPath: /proc
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: etc-hostname
          mountPath: /etc/hostname
          readOnly: true
        securityContext:
          privileged: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: etc-hostname
        hostPath:
          path: /etc/hostname
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      restartPolicy: Always
